platform :ios, "13.0"
use_frameworks! :linkage => :static
install! "cocoapods", :warn_for_unused_master_specs_repo => false

target 'RxSwiftSupplementExample' do
  pod "RxSwiftSupplement", :path => ".."

  pod 'SwiftLint', '~> 0.58.1', :configurations => ['Debug']
end